#%RAML 1.0 DataType

description: Represents a Session for a speaker
properties:
  id:
    type: integer
  name:
    type: string
  session_description: 
    type: string
  speaker_id:
    type: integer 
  level: 
    type: string
  location_id: 
    type: integer