#%RAML 1.0 NamedExample

value:
  event_id: 1
  participant_id: 1
  image_url: "https://cdn.shopify.com/s/files/1/0275/1610/8874/files/Richmond_8_b.JPG?v=1604140292"
  speaker_bio: "Joel's Bio here"
  speaker_url: "https://caspershotdogs.com/"
  twitter_handle: "@CaspersJ"