# Anypoint settings
anypoint:
  platform:
    visualizer:
      layer: Iowa Code Camp System API
      tags: Database, System API, Backend

# API and API Manager settings      
api:
  protocol: HTTPS
  manager:
    id: '${api.manager.id}'
    flowref: iowacodecamp-database-sapi-main
iowacodecamp: 
  database: 
    url: '${iowacodecamp.database.url}'
    sapi: 
      host: '${iowacodecamp.database.sapi.host}'
      port: '${iowacodecamp.database.sapi.port}'